### ISSUE TITLE
Double builds

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/scipiper#115]
I've noticed this in the past (in other repos), and am not sure of the source of the issue. Occassionally, I get double builds of a target. 

In this example, `2_nwis_pull/inout/nwis_dv_inventory.feather.ind` is a dependency of `2_nwis_pull/inout/nwis_dv_partition.feather.ind`. In the screenshot below, you can see each call to `whatNWISdata` when building the inventory (21 calls). The function binds each call into a single data frame and writes the file. When building the partition, you can see those calls happening again! This part should only rely on the existing indicator and associated file, so it's unclear why it is rebuilding. And, it's sort of _quietly_ rebuilding, as the only way I can tell it's doing that is through the progress bars. I know it's actually doing the same thing because it's taking a long time...which I presume to be actually calling NWIS.

![image](https://user-images.githubusercontent.com/15788176/63453206-b9a92600-c40d-11e9-9064-dc8a29232da8.png)

I'm using a standard pattern of loading the inventory data within the function by calling `feather::read_feather(sc_retrieve(inventory_indicator)))` where inventory_indicator is an argument in the partition function. 

I will link to this when I push my branch, but wanted to document now while I was experiencing the issue.

**Comment by limnoliver** [comment]
I was curious as to whether it would actually update the inventory file and indicator after the second build, and it did.

**Comment by jread-usgs** [comment]
does it also update the `feather` file both times too?

**Comment by limnoliver** [comment]
Yes.

**Comment by jread-usgs** [comment]
can you link to your yml?

**Comment by aappling-usgs** [comment]
I think this might be an instance of the problem targeted by #70...does that sound right to you?

**Comment by limnoliver** [comment]
@aappling-usgs yes! Thanks for pointing me here - this indeed seems like the same issue.

**Comment by aappling-usgs** [comment]
Now if only it were easier to fix...

**Comment by aappling-usgs** [comment]
Closing because this is documented in #70
