### ISSUE TITLE
should loop tasks suppressMessages by default?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/scipiper#123]
Messages are helpful and some are important. We've got a nice progress bar in `loop_tasks`, but if your code has messages (e.g., below), it kind of gets swamped. 

![image](https://user-images.githubusercontent.com/2349007/67401291-8fdabf80-f574-11e9-9514-90f34b2962fe.png)

Pros and cons to doing this of course. One simple solution is to expose an argument for suppressing messages

**Comment by jread-usgs** [comment]
I agree. And I guess that points to `scbless`, since I don't really want to re-run everything after making a change to the args in readr::read_csv()

**Comment by aappling-usgs** [comment]
Yeah, perfect use of `scbless`!
