### ISSUE TITLE
.io is 404

### ISSUE THREAD

**Issue by TrashBirdEcology** [USGS-R/scipiper#125]
[Webpage (github.io) ](https://usgs-r.github.io/scipiper/) in repo description is 404

**Comment by aappling-usgs** [comment]
Thanks. I updated it to https://usgs-r.github.io/scipiper/task_plans.html. We don't have an index file and were struggling to make that easy to build/update for some frustrating, silly reasons last time I tried. I expect to try again sometime in the future. In the meantime, vignettes (the contents of the github.io page) can be listed from R with vignette(package='scipiper') and accessed either within R or by typing in a specific vignette name into https://usgs-r.github.io/scipiper/[vignette_name].html
