### ISSUE TITLE
avoid double builds: ensure remake updates after each target

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/scipiper#70]
Consider a shared-cache workflow that uses `sc_retrieve` within specific functions. For example:
```yml
data1.rds.ind:
  command: get_push_data(target_name)
data1.rds:
  command: gd_get('data1.rds.ind')
munged.rds.ind:
  command: munge_data(target_name, 'data1.rds.ind')
```
```r
munge_data <- function(out_ind, data_ind) {
  dat <- readRDS(sc_retrieve(data_ind))
  ...
}
```

If you call `scmake('munged.rds.ind')` starting from a blank remake database, you'll see evidence that remake builds data1.rds.ind, then starts on munged.rds.ind, then _rebuilds_ data1.rds.ind while within munge_data. That's no good!

I think the reason is that sc_retrieve initiates a new inner run of `remake::make` while the outer `make` run (launched by scmake) is still going. It appears that remake may not update its target metadata one-by-one, such that even though the outer `make` call has moved onto the second target, the inner `make` call identifies the first target as being out of date because the outer `make` hasn't yet updated the database.

This problem is looking hairy to fix. The remake build/update functions involve lots of nested functions with confusingly similar names and few comments, so I'm not really sure where to start. I think this problem requires either (1) a change to remake itself or (2) an update of the remake database at the beginning of each call to scmake()...but i'm not sure the 2nd option is possible, because you'd need to know the hashes of the inputs to the targets that were just built, and that info is only available within the call stack of the `make` call that built those targets.

So...maybe we just hold our breath until we can switch to `drake` and hope we can make things work better there, either by wrapping drake or by contributing a shared-cache implementation to drake?

**Comment by jread-usgs** [comment]
ouch! is this what we were running into in vizstorm-GIF?

**Comment by aappling-usgs** [comment]
The good news is that the current functionality is not a deal-breaker for careful users. One option is to build your project by calling scmake() on each target progressively, with special attention to completing one call to scmake() before running targets that depend on any .ind files built in that call. The other option is to accept that some targets will get built a small number of times - usually just twice.

**Comment by aappling-usgs** [comment]
I don't know if we were seeing this in vizstorm-GIF, but it's entirely possible.

**Comment by lindsaycarr** [comment]
### Don't force-stop your builds when in the middle of an scmake command, a horror story.

Adding to this issue because I made a grave error today with rebuilding something that takes hours. I ran `scmake` on a downstream target that kicked off a very long data-fetching step. Rather than waiting for all the subsequent builds to finish, I stopped it mid-scmake once the target with the lengthy data fetch finished.

I was left with an updated `.ind` file, but no `build/status` file. Per @aappling-usgs's advice, I tried using `scipiper:::YAMLify_build_status('yourindfile.ind')`, but alas I must have stopped the build before remake updated it's own database, so that was not able to remedy the issue. When I check `scipiper::get_remake_status` for that target, it still says `is_current = FALSE` and `dirty = TRUE`. 

In the end, I just have to redo it and be more patient this time ...

**Comment by aappling-usgs** [comment]
OK, so I had an epiphany on the dog walk this morning, though it seems too good to be true:

What if we move all the getter calls (`gd_get`, `s3_get`, etc.) into their own remake file that's _disconnected_ from all other remake files, then always call `sc_retrieve` with that disconnected remake file specified? I think this should be safe because the main pipeline should only ever call `sc_retrieve` within functions where **remake** has already guaranteed the currentness of the .ind file, right? If we did it this way, then calls to `sc_retrieve` (which is basically just a wrapper for `scmake`) would never attempt to build upstream targets; they would just take the .ind file as a static input file and not worry about how that file got created.

Does this make sense and seem safe? I'm trying it in delaware-model-prep now (hoping to address https://github.com/USGS-R/delaware-model-prep/issues/27) and it seems to be helping...

**Comment by aappling-usgs** [comment]
A couple of thoughts as I get more excited and confident about this idea:
* There's no double-build benefit to moving the getters for `in` files into the getter.yml file...but it does make it convenient for find-edit changes to a whole project. And having them all in getters.yml would take away the need to think hard about where to put each call to `gd_get` - they just all go in getters.yml.
* We could set the default `remake_file` argument in `sc_retrieve` to "getters.yml" - then there wouldn't be any extra typing involved.
* I'm calling the file "getters.yml" in delaware-model-prep today, but if we make this a standard practice, should we call it "retrievers.yml" to match `sc_retreive()`? I guess I lean slightly toward "getters" but could see a pro to either.
* It might be a mild pain to edit two .yml files simultaneously as you're adding new paired .ind/data targets...but so far it's feeling waaaay worth it for the ability to run a whole pipeline without double builds!

**Comment by jread-usgs** [comment]
If making this change, would it also be worth considering changing the default `remake_file` value in `sc_retrieve`? Or is that too dangerous w/ backwards compatibility?

**Comment by aappling-usgs** [comment]
I did suggest that above and was wondering the same thing...chewing more, I think the "danger" would be that older projects would throw a bunch of fairly clear errors (target xxx.rds not found), so it would throw an error but would fail fast and fixably.

To make the fix less painful (I think), we could use an R Option such as `scipiper.getter_file` to set the default - we already have options for `scipiper_gd_config_file`, `scipiper.remake_file`, etc. that we use in similar ways - for old projects, we'd just need to use an .Rprofile file to set that option on project opening.
