### ISSUE TITLE
vectorize test for indicator in scipiper::as_data_file

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/scipiper#71]
I can give this function a vector of .ind filepaths (and it works as expected), but the warning pops up:
```
Warning message:
In if (!is_ind_file(ind_file, ind_ext = ind_ext)) { :
  the condition has length > 1 and only the first element will be used
```

**Comment by aappling-usgs** [comment]
hmm, this wasn't resolved as of closing of https://github.com/USGS-R/scipiper/issues/32?

**Comment by jread-usgs** [comment]
You are right, and this is redundant with that one.
