### ISSUE TITLE
integrate one-to-many into task tables

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/scipiper#80]
Sounds like @jread-usgs has an idea for how to more formally integrate his current one-to-many workflow (https://github.com/USGS-R/scipiper/issues/74) into the loop_tasks/task_makefile workflow - let's do it!

**Comment by jread-usgs** [comment]
@aappling-usgs I'm having trouble thinking about what this issue covers. Do you remember or have other notes?

**Comment by aappling-usgs** [comment]
@jread-usgs I just forwarded you an email thread with the only info I can dig up on this.

**Comment by aappling-usgs** [comment]
Sounds like we really don't have any ideas at the moment for how to enhance what can already be done, which is a lot (see #74).
